server:
  port: 8888
  servlet:
    context-path: /hk

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect


mybatis:
  configuration.callSettersOnNulls: true
  #typeAliasesPackage: com.xdd.entity
  mapper-locations: classpath:mapper/*.xml

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/gjp?characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=457854
#
#spring.jpa.show-sql= true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.jackson.serialization.indent_output=false
